name: build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        target:
          - windows-amd64
          - linux-amd64-musl
    name: Build
    runs-on: ${{ matrix.platform }}
    env:
      GOPROXY: https://proxy.golang.org,direct

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set vars
        shell: bash
        run: |
          echo "SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
          echo "BUILT_AT=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_ENV"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup web
        run: bash build.sh dev web

      - name: Build
        uses: go-cross/cgo-actions@v1
        with:
          targets: ${{ matrix.target }}
          musl-target-format: $os-$musl-$arch
          out-dir: build
          x-flags: |
            github.com/alist-org/alist/v3/internal/conf.BuiltAt=${{ env.BUILT_AT }}
            github.com/alist-org/alist/v3/internal/conf.GitAuthor=${{ github.actor }}
            github.com/alist-org/alist/v3/internal/conf.GitCommit=${{ github.sha }}
            github.com/alist-org/alist/v3/internal/conf.Version=dev
            github.com/alist-org/alist/v3/internal/conf.WebVersion=dev

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: alist_${{ env.SHA }}_${{ matrix.target }}
          path: build/*
